
-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Ven 14 Juillet 2017 à 03:40
-- Version du serveur: 10.1.24-MariaDB
-- Version de PHP: 5.2.17

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `u457743387_demo`
--

-- --------------------------------------------------------

--
-- Structure de la table `chon_de`
--

CREATE TABLE IF NOT EXISTS `chon_de` (
  `id` int(11) NOT NULL,
  `mon` varchar(256) CHARACTER SET latin1 NOT NULL,
  `ma_mon` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_icelandic_ci;

--
-- Contenu de la table `chon_de`
--

INSERT INTO `chon_de` (`id`, `mon`, `ma_mon`) VALUES
(2, 'sinh', 222),
(1, 'ly', 105),
(5, 'hoa', 102);

-- --------------------------------------------------------

--
-- Structure de la table `generator`
--

CREATE TABLE IF NOT EXISTS `generator` (
  `id` int(11) NOT NULL,
  `qno` int(11) NOT NULL,
  `question` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `opt1` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `opt2` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `opt3` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `opt4` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `ans` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `id_de` int(11) NOT NULL,
  `ma_de` varchar(11) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Contenu de la table `generator`
--

INSERT INTO `generator` (`id`, `qno`, `question`, `opt1`, `opt2`, `opt3`, `opt4`, `ans`, `id_de`, `ma_de`) VALUES
(41, 41, 'Để loại bỏ khí CH<sub>3</sub>NH<sub>2</sub> có lẫn trong khí C<sub>2</sub>H<sub>2</sub>. Ta dẫn hổn hợp khí trên qua lượng dư dung dịch nào sau đây?', 'Br<sub>2</sub>', 'NaOH', 'AgNO<sub>3</sub>/NH<sub>3</sub>', 'HCl', 'HCl', 5, '102'),
(40, 40, 'Cho các phát biểu sau:<br>(1) Phản ứng nhiệt phân hoàn toàn các muối Nitrat sản phẩm thu được luôn có chất rắn<br>(2) Có thể tồn tại dung dịch có chất: Fe(NO<sub>3</sub>)<sub>2</sub>, H<sub>2</sub>SO<sub>4</sub>, NaCl<br>(3) Sục khí CO<sub>2</sub> dư vào dung dịch NaAlO<sub>2</sub> thấy kết tủa xuất hiện<br>(3) Có thể dùng axit H<sub>2</sub>SO<sub>4</sub> đặc để làm khô khí amoniac<br>(5) Có thể thu khí Cl<sub>2</sub> bằng phương pháp đẩy nước<br>Số phát biểu <b>sai</b> là', '3', '5', '4', '2', '2', 5, '102'),
(39, 39, 'Cho hỗn hợp A gồm 10,8 gam ancol benzylic và 21,6 gam p-crezol tác dụng với dung dịch Br<sub>2</sub> dư. Khối lượng kết tủa thu được sau phản ứng', '88,7 gam', '53,2 gam', '34,5 gam', '103,5 gam', '53,2 gam', 5, '102'),
(38, 38, 'X là nguyên tố thuộc chu kì 3  trong bảng tuần hoàn và X tạo hợp chất khí với hiđro có công thức H<sub>2</sub>X. Phát biểu nào dưới đây <b>không</b> đúng.', 'Khí H<sub>2</sub>X có mùi đặc trưng.', 'Ở trạng thái cơ bản, nguyên tử X có 10 electron ở phân lớp  p. ', 'X là nguyên tố lưu huỳnh (S).', 'X có thể là nguyên tố kim loại.', 'X là nguyên tố lưu huỳnh (S).', 5, '102'),
(37, 37, 'Trộn 2 dung dịch: Ba(HCO<sub>3</sub>)<sub>2</sub>; NaHSO<sub>4</sub> có cùng nồng độ mol/l với nhau theo tỷ lệ thể tích 1:1 thu được kết tủa X và dung dịch Y. Hãy cho biết các ion có mặt trong dung dịch Y. (Bỏ qua sự thủy phân của các ion và sự điện ly của nước).', 'Na<sup>+</sup>, HCO<sub>3</sub><sup>-</sup>', 'Na<sup>+</sup>, HCO<sub>3</sub><sup>-</sup>', 'Ba<sup>2+</sup>, HCO<sub>3</sub><sup>-</sup> và Na<sup>+</sup>', 'Na<sup>+</sup>, SO<sub>4</sub><sup>2-</sup><br>', 'Ba<sup>2+</sup>, HCO<sub>3</sub><sup>-</sup> và Na<sup>+</sup>', 5, '102'),
(36, 36, 'Cho 6 gam một axit cacboxylic đơn chức vào dung dịch KHCO<sub>3</sub> dư, đếm phản ứng hoàn toàn, thu được 2,24 lít khí CO<sub>2</sub> ở đktc. Phần trăm khối lượng của cacbon trong axit trên có giá trị là', '50%', '60%', '40%', '25%', '60%', 5, '102'),
(35, 35, 'Cho 0,01 mol amino axit X tác dụng với HCl thì dùng hết 80 ml dung dịch HCl 0,125M và thu được 1,835 gam muối khan. Còn khi cho 0,01 mol X tác dụng với dung dịch NaOH thì cần dùng 25 gam dung dịch NaOH 3,2%. Công thức của X là', '(NH<sub>2</sub>)C<sub>3</sub>H<sub>5</sub>COOH', 'H<sub>2</sub>N-C<sub>2</sub>H<sub>4</sub>-COOH', 'H<sub>2</sub>N-C<sub>3</sub>H<sub>6</sub>-COOH', 'H<sub>2</sub>NC<sub>3</sub>H<sub>5</sub>(COOH)<sub>2</sub>', '(NH<sub>2</sub>)C<sub>3</sub>H<sub>5</sub>COOH', 5, '102'),
(34, 34, 'Thủy phân hoàn toàn 14,6 gam Gly-Ala bằng dung dịch NaOH, t<sup>o</sup> sau khi kết thúc phản ứng thu được m gam hỗn hợp muối. Giá trị của m là?', '22,6 gam', '37,6 gam', '20,8 gam', '16,8 gam', '37,6 gam', 5, '102'),
(33, 33, 'Có 50 ml dung dịch chứa hỗn hợp KOH 0,05M và Ba(OH)<sub>2</sub> 0,025M người ta thêm V ml dung dịch HCl 0,16M vào 50 ml dung dịch trên thu được dung dịch mới  có pH = 2. Vậy giá trị của V là', '40,45 ml', '45,67 ml', '30,33 ml', '36,67 ml', '36,67 ml', 5, '102'),
(32, 32, 'X là một anđehit mạch hở có số nguyên tử cacbon trong phân tử nhỏ hơn 4. Cho 1 mol X tác dụng với lượng dư dung dịch AgNO<sub>3</sub> trong NH<sub>3</sub> thu được 2 mol Ag. Mặt khác, 1 mol X phản ứng tối đa với 2 mol H<sub>2</sub> (Ni, t<sup>o</sup>C). Phân tử khối của X là', '56', '44', '72', '54', '72', 5, '102'),
(30, 30, 'Đun nóng 23 gam ancol etylic với 24 gam axit axetic (xúc tác H<sub>2</sub>SO<sub>4</sub> đặc) thu được 28,16 gam este. Hiệu suât của phản ứng este hóa là', '64%.', '81,68%.', '85,23%.', '80%.', '80%.', 5, '102'),
(31, 31, 'Hỗn hợp X gồm N<sub>2</sub> và H<sub>2</sub> bằng 3,6. Sau khi tiến hành phản ứng tổng hợp amoniac trong bình kín (có xúc tác bột Fe) thu được hỗn hợp khí Y có tỉ khối so với H<sub>2</sub> bằng 4. Hiệu suất phản ứng tổng hợp amoniac là', '25,00%', '18,75%', '20,00%', '10,00%', '10,00%', 5, '102'),
(29, 29, 'Hỗn hợp X gồm Fe<sub>3</sub>O<sub>4</sub> và Al có tỉ lệ mol tương ứng 1 : 3. Thực hiện phản ứng nhiệt nhôm x (không có không khí) đến khi phản ứng xảy ra hoàn toàn thu được hỗn hơp gồm:', 'Al<sub>2</sub>O<sub>3</sub>, Fe và Fe<sub>3</sub>O<sub>4</sub>.', 'Al<sub>2</sub>O<sub>3</sub> và Fe.', 'Al, Fe, Fe<sub>3</sub>O<sub>4</sub> và Al<sub>2</sub>O<sub>3</sub>.', 'Al, Fe và Al<sub>2</sub>O<sub>3</sub>.', 'Al, Fe và Al<sub>2</sub>O<sub>3</sub>.', 5, '102'),
(27, 27, 'Dẫn 4,48 lít hỗn hợp khí gồm N<sub>2</sub> và Cl<sub>2</sub>  vài dung dịch Ca(OH)<sub>2</sub> dư. Sau khi phản ứng xảy ra hoàn toàn, còn lại l,12 lít khí thoát ra. Biết thể tích các khí đó ở điều kiện tiêu chủẩn. Phần trăm thể tích của Cl<sub>2</sub> trong hỗn hợp trên là:', '11,62%.', '25,00%.', '75,00%.', '88,38%.', '75,00%.', 5, '102'),
(28, 28, 'Các dung dịch nào sau đây đều có tác dụng với Al<sub>2</sub>O<sub>3</sub>?', 'HCl, NaOH.', 'NaCl, NaOH.', 'Na<sub>2</sub>SO<sub>4</sub>, HNO<sub>3</sub>.', 'HNO<sub>3</sub>, KNO<sub>3</sub>.', 'HCl, NaOH.', 5, '102'),
(26, 26, 'Phát biểu nào sau đây là <b>sai</b>?', 'Al<sub>2</sub>O<sub>3</sub> là oxit lưỡng tính.', 'Bột Al tự bốc cháy khi tiếp xúc với khí Cl<sub>2</sub>.', 'Al(OH)<sub>3</sub> tan được trong dung dich NH<sub>3</sub> dư.', 'Al là kim loại phổ biến nhất trong vỏ trái đất.', 'Al(OH)<sub>3</sub> tan được trong dung dich NH<sub>3</sub> dư.', 5, '102'),
(25, 25, 'Hòa tan hết 1,69 gam oleum có công thức H<sub>2</sub>SO<sub>4</sub>.3SO<sub>3</sub> vào nước dư. Trung hòa dung dịch thu được cần V ml dung dịch KOH 1M. Giá trị của V là:', '30.', '40.', '10.', '20.', '10.', 5, '102'),
(24, 24, 'Cho dãy các chất: NaOH, Sn(OH)<sub>2</sub>, Pb(OH)<sub>2</sub>, Al(OH)<sub>2</sub>, Cr(OH)<sub>3</sub>. Số chất trong dãy có tính chất lưỡng tính là:', '3.', '1.', '4.', '2.', '4.', 5, '102'),
(23, 23, 'Hai nguyên tố X, Y ở cùng nhóm A và thuộc 2 chu kì liên tiếp trong bảng tuần hoàn. Tổng số proton của 2 nguyên tử thuộc 2 nguyên tố là 44 (Z<sub>X</sub> < Z<sub>Y</sub>). Cho các phát biểu sau:<br>l. X bên trong không khí và nước.<br>2. Có thể dát X thành lát mỏng để gói thực phẩm.<br>3. X tan được trong dung dịch HCl và NaOH.<br>4. Trong công nghiệp X được điều chế bằng phương pháp điện phân nóng chảy.<br>Số phát biểu đúng:', '4.', '3.', '2.', '1.', '4.', 5, '102'),
(22, 22, 'Khi nói về kim loại hiếm, phát biểu nào sau đây là <b>sai</b>?', 'Từ Li đến Cs khả năng phản ứng với nước giảm dần.', 'Các kim loại hiếm có màu trắng bạc và có ánh kim.', 'Trong tự nhiên, các kim loại hiếm chỉ tồn tại ở dạng hợp chất.', 'Kim loại hiếm có nhiệt độ nóng chảy và nhiệt độ sôi thấp.', 'Từ Li đến Cs khả năng phản ứng với nước giảm dần.', 5, '102'),
(21, 21, 'Hòa tan hoàn toàn 1,760 gam hỗn hợp gồm Fe và kim loại X vào bằng dung dịch HCl, thu được 0,896 lít khí H<sub>2</sub>. Mặt khác, hòa tan hoàn toàn 1,760 gam hỗn hợp trên bằng dung dịch HNO<sub>3</sub> loãng (dư), thu được 0,784 lít khí NO (sản phẩm khử duy nhất). Biết các thể tích khí đều đo ở điều kiện tiêu chuẩn. Kim loai X là:', 'Al.', 'Zn.', 'Mg.', 'Cr.', 'Mg.', 5, '102'),
(20, 20, 'Cấu hình electron của nguyên tử nguyên tố X (Z<sub>X</sub>< 20) có 6 electron lớp ngoài cùng, ở trạng thái đơn chất X không tác dụng với F<sub>2</sub>. Vị trí của X trong bảng tuần hoàn là:', 'Ô số 8, chu kì 2, nhóm IVA.', 'Ô số 16, chu kì 3, nhóm VIA.', 'Ô số 8, chu kì 2, nhóm VIA.', 'Ô số 14, chu kì 3, nhóm VIA.', 'Ô số 8, chu kì 2, nhóm VIA.', 5, '102'),
(18, 18, 'Khử hoàn toàn 4,8 gam CuO bằng CO ở nhiệt độ cao, khối lượng kim loại tạo ra sau phản ứng là:', '3,84 gam.', '2,4 gam.', '4,0 gam.', '3,2 gam.', '3,84 gam.', 5, '102'),
(19, 19, 'Tên thay thế của axit cacboxylic có công thức cấu tạo thu gọn CH<sub>3</sub>CH<sub>2</sub>CH<sub>2</sub>COOH là:', 'axit propanoic.', 'axit butanoic.', 'axit butiric.', 'axit propionic.', 'axit butanoic.', 5, '102'),
(16, 16, 'Số công thức cấu tạo có cùng công thức phân tử C<sub>3</sub>H<sub>8</sub>O là:', '3.', '2.', '1.', '4.', '3.', 5, '102'),
(17, 17, 'Cho 4,68 gam một kim loại M vào nước dư, sau khi phản ứng xảy ra hoàn toàn thu được 1,344 lít khí H<sub>2</sub> (ĐKTC). Kim loại M là:', 'Ba.', 'Ca.', 'K.', 'Na.', 'K.', 5, '102'),
(13, 13, 'Cho 10 gam CaCO<sub>3</sub> vào dung dịch HCl dư, sau khi phản ứng xảy ra hoàn toàn thu được V lít CO<sub>2</sub> (ĐKTC). Giá trị của V là:', '3,36.', '2,80.', '2,24.', '1,12.', '2,24.', 5, '102'),
(14, 14, 'Chất <b>KHÔNG</b> thuộc loại phenol là:', 'Catechol.', 'Hidroquinon.', 'ancol benzylic.', 'o-crezol.', 'ancol benzylic.', 5, '102'),
(15, 15, 'Nguyên liệu chính để điều chế kim loại Na trong công nghiệp là:', 'Na<sub>2</sub>CO<sub>3</sub>.', 'NaCl.', 'NaOH.', 'NaNO<sub>3</sub>.', 'NaCl.', 5, '102'),
(12, 12, 'Hợp chất nào sau đây có tính lưỡng tính?', 'Fe(OH)<sub>2</sub>.', 'Zn(OH)<sub>2</sub>.', 'Cr(OH)<sub>2</sub>.', 'Ba(OH)<sub>2</sub>.', 'Zn(OH)<sub>2</sub>.', 5, '102'),
(11, 11, 'Triolein <b>Không</b> tác dụng với chất (hoặc dung dịch) nào sau đây?', 'Dung dịch brom.', 'Khí H<sub>2</sub> (xúc tác Ni, nung nóng).', 'Dung dịch KOH (đun nóng).', 'Kim loại Na.', 'Kim loại Na.', 5, '102'),
(10, 10, 'Cho nguyên từ của nguyên tố X có cấu hình electron ở trạng thái cơ bản là [Ar]3d<sup>10</sup>4s<sup>2</sup>. Phát biểu nào sau đây <b>không</b> đúng khi nói về X?', 'X là kim loại tan được cả trong dung dịch HCl và dung dịch NaOH.', 'Ion X<sup>2+</sup> có 10 electron ở lớp ngoài cùng.', 'X là kim loại nhóm B.', 'X là nguyên tố thuộc chu kỳ 4.', 'Ion X<sup>2+</sup> có 10 electron ở lớp ngoài cùng.', 5, '102'),
(9, 9, 'Trong điện phân và trong ăn mòn điện hoá thì trên điện cực âm lần lượt xảy ra quá trình:', 'Đều là quá trình khử.', 'Khử và oxi hóa.', 'oxi hóa và khử.', 'Đều là quá trình oxi hóa', 'oxi hóa và khử.', 5, '102'),
(8, 8, 'X, Y là 2 axit no, đơn chức, mạch hở, kế tiếp nhau trong dãy đồng đẳng. Cho hỗn hợp gồm 4,60 gam A và 6,0 gam B tác dụng hết với kim loại Na thu được 2,24 lít H<sub>2</sub> (đktc). Công thức phân tử của X, Y lần lượt là:', 'C<sub>3</sub>H<sub>7</sub>COOH và C<sub>4</sub>H<sub>9</sub>COOH.', 'HCOOH và CH<sub>3</sub>COOH.', 'CH<sub>3</sub>COOH và C<sub>2</sub>H<sub>5</sub>COOH.', 'C<sub>2</sub>H<sub>5</sub>COOH và C<sub>3</sub>H<sub>7</sub>COOH.', 'CH<sub>3</sub>COOH và C<sub>2</sub>H<sub>5</sub>COOH.', 5, '102'),
(7, 7, 'Dung dịch chẩt nào trong các chất dưới đây <b>không</b> làm đổi màu quỳ tím?', 'CH<sub>3</sub>NH<sub>2</sub>.', 'CH<sub>3</sub>COONa.', 'H<sub>2</sub>NCH<sub>2</sub>COOH.', 'HOOCCH<sub>2</sub>CH<sub>2</sub>CH(NH<sub>2</sub>)COOH.', 'H<sub>2</sub>NCH<sub>2</sub>COOH.', 5, '102'),
(1, 1, 'Saccarozơ thuộc loại', 'polisaccarit.', 'đissaccarit.', 'ancol đa chức.', 'monosaccarit.', 'đissaccarit.', 5, '102'),
(2, 2, 'Nguyên liệu chính dùng để sản xuất nhôm là', 'quặng manhetit.', 'quặng pirit.', 'quặng đôlômit.', 'quặng boxit.', 'quặng boxit.', 5, '102'),
(3, 3, 'Khi điện phân NaCl nóng chảy (điện cực trơ), tại catot xảy ra', 'sự khử ion Cl<sup>-</sup>.', 'sự khử ion Na<sup>+</sup>.', 'sự oxi hoá ion Cl<sup>-</sup>.', 'sự oxi hoá ion Na<sup>+</sup>.', 'sự khử ion Na<sup>+</sup>.', 5, '102'),
(4, 4, 'etilen không tác dụng với chất nào sau đây', 'nước brom', 'H<sub>2</sub> (xúc tác Ni, đun nóng)', 'H<sub>2</sub>O (xúc tác H<sup>+</sup>, đun nóng)', 'NaOH', 'NaOH', 5, '102'),
(5, 5, 'Cho các phương trình sau: <br><img src="img/De5_6.png" alt="de thi mon hoa so 5 hinh cau 6" title="hinh cau 6 de thi mon hoa so 5" width="100%"><br>Các cân bằng chuyển dịch theo chiều thuận khi tăng áp suất là:', '1, 4.', '2, 3, 5.', '2, 3.', '1, 5.', '2, 3.', 5, '102'),
(6, 6, 'Hai chất X và Y là đồng phân của nhau, X, Y chỉ chứa C, H, O trong đó hiđro chiếm 2,439% về khối lượng. Khi đốt cháy X thu được số mol nước bằng số mol X đem đốt cháy. Biết rằng: 1,0 mol X phản ứng vừa hết với 3 mol AgNO<sub>3</sub> trong dung dịch NH<sub>3</sub> còn 1,0 mol Y phản ứng vừa hết 4,0 mol AgNO<sub>3</sub> trong dung dịch NH<sub>3</sub> Khối lượng kết tủa thu được khi cho hỗn hợp chứa 0,15 mol X và 0,10 mol Y tác dụng với lượng dư AgNO<sub>3</sub>/NH<sub>3</sub> đun nóng.', '108,6.', '86,4.', '75,6.', '108,9.', '108,9.', 5, '102'),
(42, 42, 'Cho dãy các chất :Al<sub>2</sub>O<sub>3</sub> , AlCl<sub>3</sub>, Al(OH)<sub>3</sub>, Cr(OH)<sub>3</sub>, Cr<sub>2</sub>O<sub>3</sub> Số chất trong dãy vừa phản ứng được với\r\ndung dịch NaOH loãng, vừa phản ứng được với dung dịch HCl là', '4', '3', '2', '1', '3', 5, '102'),
(43, 43, 'Hợp chất nào sau đây <b>không</b> có khả năng làm mất màu dung dịch nước brom?', 'Glixerol.', 'Axit acrylic', 'Phenol', 'Glucozơ.', 'Glixerol.', 5, '102'),
(44, 44, 'Cho 47,4 gam phèn nhôm-kali (K<sub>2</sub>SO<sub>4</sub>. Al<sub>2</sub>(SO<sub>4</sub>)<sub>3</sub>. 24H<sub>2</sub>O) vào nước thu được dung dịch X. Cho 200 ml\r\ndung dịch Ba(OH)<sub>2</sub> 0,75M vào dung dịch X thì thu được bao nhiêu gam kết tủa?', '54,4 gam', '73,2 gam', '42,75 gam', '46,6 gam', '42,75 gam', 5, '102'),
(45, 45, 'Glixin <b>không</b> phản ứng với chất nào dưới đây?', 'Axit axetic', 'Axit clohiđric', 'Natri hiđroxit', 'Axit nitrơ', 'Axit axetic', 5, '102'),
(46, 46, 'Chất nào sau đây không làm mất màu dung dịch KMnO4 ở điều kiện thường?', 'Propen', 'Toluen', 'Axetilen', 'Stiren', 'Toluen', 5, '102'),
(47, 47, 'Hiđrocacbon X ở thể khí trong điều kiện thường, Cho X lội từ từ qua dung dịch Br<sub>2</sub> dư thấy khối lượng\r\nbình đựng dung dịch Br<sub>2</sub> tăng 2,6 gam và có 0, 15 mol Br<sub>2</sub> phản ứng. X là hiđrocacbon nào dưới đây?', 'Etilen', 'Axetilen', 'Vinyl axetilen.', 'Butilen', 'Vinyl axetilen.', 5, '102'),
(48, 48, 'Đun nóng 0,1 mol este đơn chức X với 135 ml dung dịch NaOH 1M. Sau khi phản ứng xảy ra hoàn toàn,\r\ncô cạn dung dịch thu được ancol etylic và 9,6 gam chất rắn khan. Công thức cấu tạo của X:', 'C<sub>2</sub>H<sub>5</sub>COOC<sub>2</sub>H<sub>5</sub>.', 'C<sub>2</sub>H<sub>5</sub>COOC<sub>2</sub>H<sub>5</sub>.', 'CH<sub>3</sub>COOC<sub>2</sub>H<sub>5</sub>.', 'C<sub>2</sub>H<sub>5</sub>COOCH<sub>3</sub>.', 'CH<sub>3</sub>COOC<sub>2</sub>H<sub>5</sub>.', 5, '102'),
(49, 49, 'Cho 5,7 gam hổn hợp bột gồm Mg, Al, Zn, Cu tác dụng hoàn toàn với oxi dư thu được hổn hợp rắn Y có\r\nkhối lượng là 8,1 gam. Hòa tan Y bằng lượng vừa đủ dung dịch hổn hợp HCl 0,5M và H<sub>2</sub>SO<sub>4</sub> 0,25M, thu được\r\ndung dịch Z. Cô cạn dung dịch Z thì lượng muối khan thu được là?', '18,225 gam', '11,9625 gam', '14,3625 gam', '20,656 gam', '18,225 gam', 5, '102'),
(50, 50, 'Phát biểu nào sau đây không chính xác?', 'Khí CO<sub>2</sub> là khí độc và là nguyên nhân chính gây hiện tượng hiệu ứng nhà kính.', 'Một lượng rất nhỏ khí O<sub>3</sub> có trong không khí, có tác dụng làm cho không khí trong lành hơn.', 'Khí thải ra khí quyển freon (chủ yếu là CFCl<sub>3</sub>, CF<sub>2</sub>Cl<sub>2</sub>) phá hủy tầng ozon.', 'Thủy ngân là kim loại dễ bay hơi và rất độc, người ta dùng bột lưu huỳnh để phòng độc thủy ngân.', 'Khí CO<sub>2</sub> là khí độc và là nguyên nhân chính gây hiện tượng hiệu ứng nhà kính.', 5, '102'),
(51, 1, 'Loại ARN nào mang bộ ba đối mã (anticodon) ?', 'tARN.', 'rARN.', 'mARN.', 'Tất cả các loại ARN.', 'tARN.', 2, '222'),
(52, 2, 'Một loài có bộ NST 2n=14. Hãy cho biết số lượng NST ở thể một nhiễm là', '12.', '15.', '13.', '16.', '13.', 2, '222'),
(53, 3, 'Sự nhân đôi ADN ở sinh vật nhân thực khác với sự nhân đôi ADN ở sinh vật nhân sơ về<br>\r\n		1. Chiều tổng hợp <br>\r\n		2. Các enzim tham gia <br>\r\n		3. Thành phần tham gia <br>\r\n		4. Số lượng các đơn vị nhân đôi <br>\r\n		5. Nguyên tắc nhân đôi<br>\r\n		Các phương án đúng là:', '1,2.', '2,3.', '2,4.', '1,5.', '2,4.', 2, '222'),
(54, 4, 'Ở một loài thực vật, xét 2 gen nằm trong nhân tế bào, mỗi gen đều có 2 alen. Cho 2 cây (P) thuần chủng khác nhau về cả 2 cặp gen giao phấn với nhau, thu được F1. Cho F1 lai với cây đồng hợp tử lặn về cả 2 cặp gen thu được Fa. Biết rằng không xẩy ra đột biến và nếu có hoán vị gen thì f = 50%, sự biểu hiện của gen không phụ thuộc điều kiện môi trường. Theo lí thuyết, tỉ lệ kiểu hình nào sau đây không phù hợp với Fa?', '1:2:1', '3:3:1:1', '3:1', '1:1:1:1', '3:3:1:1', 2, '222'),
(55, 5, 'Ở ngô, tính trạng màu sắc hạt do 2 gen không alen quy định. Cho ngô hạt trắng giao phấn với hạt trắng thu được F1 có 962 hạt trắng: 241 hạt vàng: 80 hạt đỏ. Theo lí thuyết, tỉ lệ hạt trắng ở F1 đồng hợp tử về cả hai cặp gen trong tổng số hạt trắng ở F1 là:', '3/16', '1/8', '1/6', '3/8', '1/6', 2, '222'),
(56, 6, 'Cho biết mỗi cặp tính trạng do một cặp gen quy định và trội hoàn toàn. Tần số hoán vị giữa A và B là 20%. Ở phép lai:<img src="img/De2_6.PNG" alt="hinh-cau-6-de-2" title="hinh 6 de 2 mon sinh thi tn" > theo lí thuyết thì kiểu hình aaB-D- ở đời con chiếm tỉ lệ:', '75%', '25%', '56,25%', '3,75%', '3,75%', 2, '222'),
(57, 7, 'Khi nói về mã di truyền, phát biểu nào sau đây là đúng ?', 'Tính thoái hóa của mã di truyền có nghĩa là mỗi codon có thể mã hóa cho nhiều loại aa', 'Với 3 loại nucleotit A, U, G có thể tạo ra 24 loại bộ ba mã hóa aa', 'Tính phổ biến của mã di truyền có nghĩa là tất cả các loài đều có chung một bộ mã di truyền', 'Ở sinh vật nhân thực, codon 3’AUG5’ có chức năng khởi đầu dịch mã và mã hóa axit amin metionin', '25%', 2, '222'),
(58, 8, 'Phương pháp lai và phân tích con lai của Menden gồm các bước sau :<br>\r\n		1. Sử dụng toán xác suất để phân tích kết quả lai, sau đó đưa ra giả thuyết khoa học<br>\r\n		2. Lai các dòng thuần chủng khác nhau bởi một hay nhiều tính trạng rồi phân tích kết quả lai ở đời F1, F2, F3 <br>\r\n		3. Tạo các dòng thuần chủng khác nhau về từng tính trạng bằng cách cho cây tự thụ phấn qua nhiều thế hệ <br>\r\n		4. Tiến hành thí nghiệm chứng minh giả thuyết của mình <br>\r\n		Trình tự các bước đúng :', '3&rarr;2&rarr;1&rarr;4', '3&rarr;2&rarr;4&rarr;1', '3&rarr;4&rarr;1&rarr;2', '1&rarr;3&rarr;2&rarr;4', 'Tính thoái hóa của mã di truyền có nghĩa là mỗi codon có thể mã hóa cho nhiều loại aa', 2, '222'),
(59, 9, 'Cho các sự kiện diễn ra trong quá trình dịch mã ở tế bào nhân thực như sau:<br>\r\n		1. Bộ ba đối mã của phức hợp met-tARN gắn bổ sung với codon mở đầu trên mARN<br>\r\n		2. Tiểu vị lớn của riboxom kết hợp với tiểu đơn vị bé tạo thành riboxom hoàn chỉnh<br>\r\n		3. Tiểu đơn vị bé của riboxom gắn với mARN ở vị trí nhận biết đặc hiệu<br>\r\n		4. Codon thứ nhất trên mARN gắn bổ sung với anticodon với phức hệ aa1-tARN<br>\r\n		5. Riboxom dịch đi 1 codon trên mARN theo chiều 5’-3’<br>\r\n		6. Hình thành liên kết peptit giữa aa mở đầu và aa 1<br>\r\n		Trình tự đúng:', '3-1-2-4-6-5', '5-2-1-4-6-3', '1-3-2-4-6-5', '2-1-3-4-6-5', '3-1-2-4-6-5', 2, '222'),
(60, 10, 'Cho các sự kiện diễn ra trong phiên mã<br>\r\n		1. ARN polimeraza bắt đầu tổng hợp mARN tại vị trí đặc hiệu<br>\r\n		2. ARN polimeraza bám vào vùng điều hòa làm gen tháo xoắn để lộ mạch gốc có chiều 3’-5’<br>\r\n		3. ARN polimeraza trượt dọc theo mạch mã gốc của gen có chiều 3’-5’<br>\r\n		4. Khi ARN polimeraza di chuyển tới cuối gen, gặp tín hiệu kết thúc thì nó dừng phiên mã<br>\r\n		Trình tự đúng khi nói về quá trình phiên mã là', '1-2-3-4', '2-1-3-4', '2-3-1-4', '1-3-2-4', '2-1-3-4', 2, '222'),
(61, 11, 'Cho các biện pháp<br>\r\n		1- Dung hợp tế bào trần <br>\r\n		2- Cấy truyền phôi.<br>\r\n		3- Nhân bản vô tính.<br>\r\n		4- Nuôi cấy hạt phấn sau đó lưỡng bội hóa.<br>\r\n		5- Tự thụ phấn liên tục từ 5 đến 7 đời kết hợp với chọn lọc.<br>\r\n		Phương pháp được sử dụng để tạo ra dòng thuần chủng là:', '4,5.', '2,3,4.', '3,4,5.', '1,2,3,4,5.', '4,5.', 2, '222'),
(62, 12, 'Khi nói về ưu thế lai, phát biểu nào sau đây không đúng? ', 'Một trong những giả thuyết để giải thích cơ sở di truyền của ưu thế lai được nhiều người thừa nhận là giả thuyết siêu trội', 'Để tạo ra những con lai có ưu thế lai cao về một số đặc tính tốt nào đó, người ta thường bắt đầu bằng cách tạo ra những dòng thuần chủng khác nhau', 'Trong một số trường hợp, lai giữa hai dòng nhất định thu được con lai không có ưu thế lai, nhưng nếu cho con lai này lai với dòng thứ ba thì đời con lại có ưu thế lai.', 'Người ta tạo ra những con lai khác dòng có ưu thế lai cao để sử dụng cho việc nhân giống.', 'Người ta tạo ra những con lai khác dòng có ưu thế lai cao để sử dụng cho việc nhân giống.', 2, '222'),
(63, 13, 'Cho các biện pháp sau:<br>\r\n		1. Bảo vệ môi trường sống trong sạch.<br>\r\n		2. Tư vấn di truyền.<br>\r\n		3. Sàng lọc trước sinh.<br>\r\n		4. Liệu pháp gen.<br>\r\n		5. Mở các trung tâm bảo trợ xã hội dành cho người bị tật, bệnh di truyền.<br>\r\n		Số phương án đúng để bảo vệ vốn gen của loài người là:', '5.', '4.', '2.', '3.', '4.', 2, '222'),
(64, 14, 'Giả sử một gen đang nhân đôi trong môi trường có 1 phân tử 5- Brôm Uraxin (5-BU) thì sau 6 lần nhân đôi thì số lượng gen đột biến bị đột biến thay thế A-T bằng G−X và số gen gen bình thường lần lượt là bao nhiêu? Biết rằng 5-BU chỉ có một lần thay đổi cấu trúc trong suốt quá trình nhân đôi của gen nói trên.', '15 và 48.', '3 và 28.', '15 và 30.', '7 và 24.', '15 và 48.', 2, '222'),
(65, 15, 'Quy trình tạo giống bằng phương pháp gây đột biến gồm có 3 trong các bước sau:<br>\r\n		I. Cho tự thụ phấn hoặc lai xa để tạo ra các giống thụần chủng.<br>\r\n		II. Chọn lọc các thể đột biến có kiểu hình mong muốn.<br>\r\n		III. Xử lý mẫu vật bằng tác nhân đột biến.<br>\r\n		IV. Tạo dòng thuần chủng.<br>\r\n		Quy trình nào sau đây là đúng nhất ?', 'II &rarr; III &rarr; IV.', 'I &rarr; III &rarr; II.', 'III &rarr; II &rarr; IV.', 'III &rarr; II &rarr; I.', 'III &rarr; II &rarr; IV.', 2, '222'),
(66, 16, 'Ở một loài ngẫu phối, thế hệ xuất phát có 100 cá thể trong đó có 64 con cái có kiểu gen AA, 32 con cái có kiểu gen Aa, 4 con đực có kiểu gen aa Ở thế hệ F2 tỉ lệ kiểu gen Aa chiếm tỉ lệ:', '5/6.', '2/25.', '35/72.', '8/25.', '35/72.', 2, '222'),
(67, 17, 'Một cơ thể có kiểu gen AaBb giảm phân phát sinh giao tử, ở một số tế bào xảy ra sự rối loạn phân ly trong giảm phân ở cặp nhiễm sắc thể chứa cặp gen Aa. Cơ thể đó có thể tạo ra số loại giao tử tối đa là', '12', '4', '8', '6', '12', 2, '222'),
(68, 18, 'Một cây có kiểu gen (AB/ab)x(De/dE) tự thụ phấn, đời con thu được nhiều loại kiểu hình trong đó kiểu hình trội về 4 tính trạng là 33,165%. Nếu khoảng cách di truyền giữa A và B 1à 20cM thì khoảng cách di truyền giữa D và e là:', '30 cM.', '10 cM.', '20 cM.', '40 cM.', '10 cM.', 2, '222'),
(69, 19, 'Loại đột biến làm tăng số loại alen trong cơ thể là:', 'đột biến đa bội.', 'đột biến lặp đoạn nhiễm sắc thể.', 'đột biến gen.', 'đột biến lệch bội.', 'đột biến gen.', 2, '222'),
(70, 20, 'Ở cà chua, alen A quy định quả đỏ trội hoàn toàn so với alen a quy định quả vàng, alen B quy định thân cao trội hoàn toàn so với a quy định thân thấp. Cho giao phối cây lưỡng bội thuần chủng khác nhau về hai tính trạng trên thu được F1. Xử lí cônsixin với các cây F1 sau đó cho hai cây F1 giao phấn với nhau thu được đời con F2 có kiểu hình phân li theo tỉ lệ 121 : 11 :11 : 1. Các phép lai có thể cho kết quả trên gồm:<br>\r\n		1. AAaaBBbb X AaBb.<br>\r\n		2. AAaaBb X AaBBbb.<br>\r\n		3. AaBbbb x AAaaBBbb.<br>\r\n		4.AAaaBBbb X AaaaBbbb.<br>\r\n		5. AaaaBBbb X AAaaBb.<br>\r\n		6. AaBBbb X AaaaBbbb.<br>\r\n		Có mấy trường hợp mà cặp bố mẹ F1 không phù hợp với kết quả F2?', '4.', '1.', '3.', '2.', '4.', 2, '222'),
(71, 21, 'Khi nói về cơ chế dịch mã ở sinh vật nhân thực, nhận định nào sau đây không đúng?', 'Khi dịch mã, ribôxôm chuyển dịch theo chiều 5`→3` trên phân tử mARN.', 'Trong cùng một thời điểm có thể có nhiều ribôxôm tham gia dịch mã trên một phân tử mARN', 'Khi dịch mã, ribôxôm chuyển dịch theo chiều 3`→5` trên phân tử mARN.', 'Axit amin mở đầu trong quá trình dịch mã là mêtiônin.', 'Khi dịch mã, ribôxôm chuyển dịch theo chiều 3`→5` trên phân tử mARN.', 2, '222'),
(72, 22, 'Cho biết mỗi gen quy định một tính trạng và gen trội hoàn toàn. Ở đời con của phép lai AaBBDd × AaBbdd có tỉ lệ kiểu gen, tỉ lệ kiểu hình lần lượt là', '2 : 2 : 2 : 2 : 1 : 1 : 1 : 1 và 3 : 3 : 1 : 1.', '2 : 2 : 1 : 1 : 1 : 1 : 1 : 1 và 3 : 3 : 1 : 1.', '2 : 2 : 2 : 2 : 1 : 1 : 1 : 1 : 1 : 1 : 1 : 1 và 3 : 3 : 1 : 1.', '2 : 2 : 1 : 1 : 1 : 1 : 1 : 1 và 9 : 3 : 3 : 1.', '2 : 2 : 2 : 2 : 1 : 1 : 1 : 1 và 3 : 3 : 1 : 1.', 2, '222'),
(73, 23, 'Bản chất của quy luật phân li theo Menđen là', 'Sự phân li đồng đều của các nhân tố di truyền trong mỗi cặp nhân tố di truyền.', 'Sự phân li đồng đều các alen của từng cặp alen năm trên các cặp nhiễm sắc thể tương đồng khác nhau.', 'Sự phân li độc lập của các cặp nhân tố di truyền, giảm phân diễn ra bình thường trong quá trình hình thành giao tử.', 'Thế hệ P thuần chủng, tính trạng trội phải trội hoàn toàn, số lượng cá thể phân tích phải đủ lớn.', 'Sự phân li đồng đều của các nhân tố di truyền trong mỗi cặp nhân tố di truyền.', 2, '222'),
(74, 24, 'Cho biết gen A : thân cao; gen a : thân thấp. Các cơ thể đem lai đều giảm phân bình thường. Phép lai có tỷ lệ kiểu hình 11 cao : 1 thấp là :', 'AAAa x AAA', 'AAaa x Aa', 'AA x AAaa', 'AAaa x AAaa', 'AAaa x AAaa', 2, '222'),
(75, 25, 'Theo quan niệm của Đacuyn, nguồn nguyên chủ yếu của quá trình tiến hóa là', 'đột biến cấu trúc nhiễm sắc thể', 'đột biến gen', 'biến dị cá thể', 'đột biến số lượng nhiễm sắc thể', 'đột biến gen', 2, '222'),
(76, 26, 'Ba tế bào sinh tinh có kiểu gen AaBbEe tiến hành giảm phân bình thường để tạo tinh trùng, theo lí thuyết số loại tinh trùng tối đa có thể tạo ra là bao nhiêu?', '16', '8', '6', '2', '6', 2, '222'),
(77, 27, 'Các ví dụ nào sau đây thuộc cơ chế cách li trước hợp tử?<br>\r\n		(1) Ngựa cái giao phối với lừa đực sinh ra con la không có khả năng sinh sản.<br>\r\n		(2) Cây thuộc loài này thường không thụ phấn được cho cây thuộc loài khác.<br>\r\n		(3) Trứng nhái thụ tinh với tinh trùng cóc tạo ra hợp tử nhưng hợp tử không phát triển.<br>\r\n		(4) Các loài ruồi giấm khác nhau có tập tính giao phối khác nhau.<br>\r\n		Đáp án đúng là:', '(2), (4)', '(1), (3)', '(1), (4)', '(2), (3)', '(2), (3)', 2, '222'),
(78, 28, 'Quá trình nào sau đây sẽ tạo ra các alen mới?', 'Đột biến cấu trúc NST', 'Đột biến gen', 'Đột biến số lượng NST', 'Hoán vị gen', 'Đột biến gen', 2, '222'),
(79, 29, 'Một gen có 1824 liên kết hiđrô. Trên mạch 1 của gen có T = A; X = 2T ; G= 3A. Gen bị đột biến điểm làm giảm 1 liên kết hiđrô. Số nuclêôtit loại A của gen đột biến là', '193', '191', '97', '95', '97', 2, '222'),
(80, 30, 'Ở một loài cỏ, quần thể ở phía trong bờ sông ra hoa kết hạt đúng vào mùa lũ về, quần thể ở bãi bồi ven sông ra hoa kết hạt trước mùa lũ về nên không giao phấn được với nhau. Đây là ví dụ về', 'cách li thời gian', 'cách li tập tính', 'cách li cơ học', 'cách li nơi ở', 'cách li tập tính', 2, '222'),
(81, 31, 'Theo thuyết tiến hóa hiện đại, phát biểu nào sau đây <b>không</b> đúng?', 'Chọn lọc tự nhiên là nhân tố qui định chiều hướng và nhịp điệu tiến hóa.', 'Quá trình tiến hóa nhỏ diễn ra trên quy mô quần thể và diễn biến không ngừng dưới tác động\r\ncủa các nhân tố tiến hóa.', 'Các yếu tố ngẫu nhiên làm nghèo vốn gen quần thể, giảm sự đa dạng di truyền nên không có vai\r\ntrò đối với tiến hóa.', 'Khi không có tác động của đột biến, chọn lọc tự nhiên và di - nhập gen thì tần số alen và thành\r\nphần kiểu gen của quần thể vẫn có thể bị thay đổi.', 'Các yếu tố ngẫu nhiên làm nghèo vốn gen quần thể, giảm sự đa dạng di truyền nên không có vai\r\ntrò đối với tiến hóa.', 2, '222'),
(82, 32, 'Ở một loài thực vật, xét 2 tính trạng, mỗi tính trạng đều do một gen có 2 alen quy định, alen\r\ntrội là trội hoàn toàn. Hai gen này cùng nằm trên một nhiễm sắc thể thường, hoán vị gen xảy ra ở cả\r\nquá trình phát sinh giao tử đực và giao tử cái. Giao phấn hai cây thuần chủng, tương phản về kiểu gen,\r\nmỗi cây chỉ trội về 1 trong 2 tính trạng trên (P), thu được F<sub>1</sub>. Cho F<sub>1</sub> giao phấn với nhau, thu được F<sub>2</sub>.\r\nBiết rằng không xảy ra đột biến. Theo lí thuyết, kết luận nào sau đây về F<sub>2</sub> <b>sai?</b>', 'Có 10 loại kiểu gen.', 'Kiểu hình trội về 2 tính trạng luôn chiếm tỉ lệ lớn nhất.', 'Kiểu hình lặn về 2 tính trạng luôn chiếm tỉ lệ nhỏ nhất.', 'Có 2 loại kiểu gen dị hợp tử về 1 cặp gen.', 'Có 2 loại kiểu gen dị hợp tử về 1 cặp gen.', 2, '222'),
(83, 33, 'Ở đậu Hà Lan, alen A quy định thân cao trội hoàn toàn so với alen a quy định thân thấp. Thế\r\nhệ xuất phát (P) của một quần thể gồm toàn cây thân cao, trong đó tỉ lệ cây thân cao có kiểu gen dị hợp\r\ntử là 0,4. Quần thể tự thụ phấn liên tiếp qua các thế hệ. Biết rằng quần thể không chịu tác động của các\r\nnhân tố tiến hóa khác. Theo lí thuyết, ở thế hệ F<sub>2</sub> của quần thể, cây thân cao chiếm tỉ lệ', '3/4', '3/20', '17/20', '1/10', '17/20', 2, '222'),
(84, 34, 'Một loài thực vật lưỡng bội có 12 nhóm gen liên kết. Do đột biến, ở một quần thể thuộc loài\r\nnày đã xuất hiện hai thể đột biến khác nhau là thể bốn và thể tứ bội. Số lượng nhiễm sắc thể có trong\r\nmột tế bào sinh dưỡng của thể bốn và thể tứ bội này lần lượt là', '28 và 48.', '14 và 24.', '26 và 48.', '16 và 24.', '26 và 48.', 2, '222'),
(85, 35, 'Ở người alen B quy định kiểu hình hói đầu, alen b quy định kiểu hình bình thường, kiểu gen\r\nBb quy định hói đầu ở nam và bình thường ở nữ. Quan sát một quần thể cân bằng có 10% người hói\r\nđầu. Cấu trúc di truyền của quần thể là', '0,2BB : 0,1Bb : 0,7bb.', '0,01BB : 0,18Bb : 0,81bb.', '0,81BB : 0,01Bb : 0,18bb.', '0,18BB : 0,01Bb : 0,81bb.', '0,01BB : 0,18Bb : 0,81bb.', 2, '222'),
(86, 36, 'Ba tế bào sinh tinh đều có kiểu gen (AB\r\n/ab)\r\nDdEe giảm phân bình thường nhưng xảy ra hoán vị\r\ngen ở một trong ba tế bào. Theo lí thuyết, số loại giao tử tối đa được tạo ra là', '2', '4', '6', '8', '8', 2, '222'),
(87, 37, 'Cho sơ đồ phả hệ mô tả sự di truyền một bệnh ở người do một trong hai alen của một gen qui\r\nđịnh, alen trội là trội hoàn toàn.<img src="img/hinh_de_9_1.JPG" alt="hinh 37 de sinh tai thithpt.tk" title="hinh 37 de thi sinh tai trang web thithpt" width="100%"><br>Biết rằng không xảy ra đột biến mới và người đàn ông II. 4 đến từ một quần thể khác đang ở\r\ntrạng thái cân bằng di truyền có tần số alen gây bệnh là 0,2. Xác suất để IV. 10 không mang alen gây\r\nbệnh là bao nhiêu?', '1/3', '8/15', '5/11', '2/3', '8/15', 2, '222'),
(88, 38, 'Ở một loài thực vật, tính trạng màu sắc hoa do một gen có hai alen quy định. Cho cây hoa đỏ\r\nthuần chủng giao phấn với cây hoa trắng thuần chủng (P), thu được F<sub>1</sub> toàn cây hoa đỏ. F<sub>1</sub> tự thụ phấn,\r\nthu được F<sub>2</sub> có kiểu hình phân li theo tỉ lệ: 75% cây hoa đỏ : 25% cây hoa trắng. Biết rằng sự biểu hiện\r\ncủa gen không phụ thuộc vào môi trường. Dựa vào kết quả trên, hãy cho biết trong các kết luận sau, có\r\nbao nhiêu kết luận đúng?<p>(1) Đời con của một cặp bố mẹ bất kì đều có tỉ lệ kiểu gen giống tỉ lệ kiểu hình.</p><p>(2) Chỉ cần dựa vào kiểu hình cũng có thể phân biệt được cây có kiểu gen đồng hợp tử và cây có\r\nkiểu gen dị hợp tử.</p><p>(3) Nếu cho các cây hoa đỏ ở F<sub>2</sub> giao phấn với các cây hoa trắng, thu được đời con có kiểu hình\r\nphân li theo tỉ lệ 2 cây hoa đỏ : 1 cây hoa trắng.</p><p>(4) Màu sắc hoa là kết quả sự tương tác giữa các gen không alen.</p>', '4', '3', '1', '2', '1', 2, '222'),
(89, 39, 'Cho phép lai P: ♀ (AB\r\n/ab)\r\nX<sup>D</sup>X<sup>d</sup> × ♂\r\n(Ab/\r\naB)\r\nX<sup>D</sup>Y, thu được F<sub>1</sub>. Trong tổng số cá thể F<sub>1</sub>, số cá thể\r\nkhông mang alen trội của các gen trên chiếm 1%. Biết rằng không xảy ra đột biến nhưng xảy ra hoán vị\r\ngen ở 2 giới với tần số bằng nhau. Theo lí thuyết, ở F<sub>1</sub> số cá thể cái mang alen trội của cả 3 gen trên\r\nchiếm tỉ lệ', '27%', '41,25%', '13,5%', '40,5%', '27%', 2, '222'),
(90, 40, 'Ở một quần thể động vật ngẫu phối, xét một gen nằm trên nhiễm sắc thể thường gồm 2 alen,\r\nalen A trội hoàn toàn so với alen a. Dưới tác động của chọn lọc tự nhiên, những cá thể có kiểu hình lặn\r\nbị đào thải hoàn toàn ngay sau khi sinh ra. Thế hệ xuất phát (P) của quần thể này có cấu trúc di truyền\r\nlà 0,8AA : 0,2Aa. Cho rằng không có tác động của các nhân tố tiến hóa khác. Theo lí thuyết, thế hệ F<sub>4</sub>\r\ncủa quần thể này có tần số alen A là', '1/14', '1/13', '12/13', '13/14', '13/14', 2, '222'),
(91, 41, 'Ở một loài động vật lưỡng bội, tính trạng màu sắc lông do một gen nằm trên nhiễm sắc thể\r\nthường có 3 alen quy định. Alen quy định lông đen trội hoàn toàn so với alen quy định lông xám và alen quy định lông trắng; alen quy định lông xám trội hoàn toàn so với alen quy định lông trắng. Một quần thể\r\nđộng vật đang ở trạng thái cân bằng di truyền có tỉ lệ các kiểu hình là 0,51 đen : 0,24 xám : 0,25 trắng.\r\nTheo lý thuyết, phát biểu nào sau đây <b>không đúng?</b>', 'Nếu chỉ cho các con lông xám của quần thể ngẫu phối thì đời con có kiểu hình phân li theo tỉ lệ là\r\n99 xám : 1 trắng.', 'Nếu chỉ cho các con lông đen của quần thể ngẫu phối thì đời con có kiểu hình lông đen thuần chủng\r\nchiếm 100/289.', 'Tổng số con lông đen dị hợp và lông xám dị hợp của quần thể chiếm 0,62.', 'Số con lông đen có kiểu gen đồng hợp và số con lông trắng của quần thể chiếm 0,34.', 'Nếu chỉ cho các con lông xám của quần thể ngẫu phối thì đời con có kiểu hình phân li theo tỉ lệ là\r\n99 xám : 1 trắng.', 2, '222'),
(92, 42, 'Sơ đồ nào dưới đây phản ánh đúng những hiểu biết hiện nay của chúng ta về sự sao chép vật\r\nchất di truyền ở các sinh vật khác nhau và “dòng thông tin di truyền” có ở các hệ thống sinh học?<br><img src="img/hinh_de_10_2.JPG" alt="hinh 42 de sinh so 9 tai thitn" title="hinh cau 42 de sinh so 9 tai thitn" width="100%">', 'A', 'B', 'C', 'D', 'A', 2, '222'),
(93, 43, 'Ở vi khuẩn E.coli, giả sử có 5 chủng vi khuẩn bị đột biến như sau:<p>Chủng 1: Đột biến gen cấu trúc Z làm cho phân tử protein do gen này tổng hợp bị mất chức năng.</p><p>Chủng 2: Đột biến gen cấu trúc A làm cho phân tử protein do gen này tổng hợp bị mất chức năng.</p><p>Chủng 3: Đột biến gen cấu trúc Y làm cho phân tử protein do gen này tổng hợp bị mất chức năng.</p><p>Chủng 4: Đột biến gen điều hòa R làm cho gen này mất khả năng phiên mã.</p><p>Chủng 5: Đột biến vùng khởi động P làm cho vùng này bị mất chức năng.</p><p>Khi trong môi trường có đường lactose thì số chủng vi khuẩn có các gen cấu trúc <b>không</b> phiên mã là</p>', '3', '1', '4', '2', '1', 2, '222'),
(94, 44, 'Xét sự di truyền của 2 bệnh trong 1 dòng họ. Bệnh bạch tạng do gen lặn a nằm trên NST thường\r\nquy định, gen trội A qui định người bình thường. Bệnh mù màu do gen m nằm trên vùng không tương\r\nđồng của X quy định, gen trội M quy định người bình thường. Bên phía nhà vợ, anh trai vợ bị bệnh bạch\r\ntạng, ông ngoại của vợ bị bệnh mù màu, những người khác bình thường về 2 bệnh này. Bên phía nhà\r\nchồng, bố chồng bị bạch tạng, những người khác bình thường về cả hai bệnh. Xác suất cặp vợ chồng nói\r\ntrên sinh được 2 đứa con bình thường, không bị cả hai bệnh trên là', '55,34% ', '48,11%', '59,12%', '53,16%', '55,34% ', 2, '222'),
(95, 45, 'Ở 1 loài thực vật có bộ NST 2n = 14, trên mỗi NST thường khác nhau đều xét 1 gen có 2 alen.\r\nTheo lý thuyết trong loài tạo ra tối đa bao nhiêu loại kiểu gen khác nhau về đột biến thể ba?', '2916', '5103', '2187', '20412', '20412', 2, '222'),
(96, 46, 'Lai hai cây hoa màu trắng thuần chủng với nhau, thu được F<sub>1</sub> gồm toàn cây hoa màu đỏ. Cho Fl\r\ngiao phấn với nhau thu được F<sub>2</sub> gồm 56,25% cây hoa đỏ ; 43,75% cây hoa trắng. Nếu cho cây hoa đỏ F<sub>1</sub>\r\nlần lượt giao phấn với từng cây hoa trắng thì ở đời con có thể bắt gặp những tỉ lệ phân li kiểu hình nào\r\ntrong số các tỉ lệ phân li kiểu hình dưới đây?<p>(1) 9 đỏ : 7 trắng. (2) 1 đỏ : 3 trắng. (3) 1 đỏ : 1 trắng.</p><p>(4) 3 đỏ : 1 trắng. (5) 3 đỏ : 5 trắng. (6) 5 đỏ : 3 trắng.</p><p>(7) 13 đỏ : 3 trắng.  (8) 7 đỏ: 1 trắng. (9) 7 đỏ : 9 trắng.</p>', '(1), (3), (5), (7).', '(1), (3), (5).', '(2), (3), (5).', '(2), (3), (4).', '(2), (3), (5).', 2, '222'),
(97, 47, 'Người ta đem lai ngựa lông xám với ngựa lông xám có kiểu gen giống nhau được đời con có tỉ lệ\r\nkiểu hình là 9 lông xám : 2 lông đen : 1 lông hung. Nếu lấy ngựa lông xám ở P lai phân tích thì thu được\r\ntỉ lệ kiểu hình ở đời con là', '1 xám : 1 đen : 1 hung', '2 xám : 1 đen : 1 hung', '1 xám : 1 đen : 2 hung', '1 xám : 2 đen : 1 hung', '2 xám : 1 đen : 1 hung', 2, '222'),
(98, 48, 'Từ 1 tế bào xoma có bộ nhiễm sắc thể lưỡng bội 2n, nguyên phân liên tiếp 8 lần. Tuy nhiên,\r\ntrong một lần phân bào ở một tế bào con có hiện tượng tất cả các nhiễm sắc thể không phân li nên chỉ tạo\r\nra một tế bào có bộ nhiễm sắc thể 4n, tế bào 4n này và các tế bào con khác tiếp tục nguyên phân bình\r\nthường với chu kì tế bào như nhau. Kết thúc quá trình nguyên phân trên đã tạo ra 224 tế bào con. Theo lý thuyết lần nguyên phân xảy ra đột biến và tỷ lệ tế bào 4n so với tế bào 2n sinh ra ở lần cuối cùng lần lượt\r\nlà', '5 và 1/6', '5 và 1/7', '3 và 1/7', '3 và 1/6', '3 và 1/6', 2, '222'),
(99, 49, 'Ở ruồi giấm bộ NST 2n = 8. Có 1 hợp tử của loài đã nguyên phân 8 đợt liên tiếp, ở lần nguyên\r\nphân đầu tiên trước khi phân li NST đã xảy ra hiện tượng trao đổi chéo trong 1 NST kép dẫn đến lặp\r\nđoạn. Tỉ lệ số NST lặp đoạn so với NST bình thường có trong các tế bào con sinh ra cuối cùng khi các\r\nNST chưa nhân đôi là', '1/7', '1/14', '1/8', '1/16', '1/14', 2, '222'),
(100, 50, 'Cho sơ đồ phả hệ sau:<img src="img/hinh_de_10_3.JPG" alt="hinh 50 de sinh so 9 tai thitn" title="hinh cau 50 de sinh so 9 tai thitn" width="100%"><br>Sơ đồ phả hệ trên mô tả sự di truyền một bệnh ở người do một trong 2 alen của một gen quy định. Biết\r\nrằng không xảy ra đột biến mới ở tất cả các cá thể trong phả hệ. Trong những phát biểu sau có bao nhiêu\r\nphát biểu đúng?<p>(1) Gen gây bệnh là gen lặn nằm trên nhiễm sắc thể giới tính.</p><p>(2) Những người không mắc bệnh ở thế hệ thứ 2 đều có kiểu gen giống nhau.</p><p>(3) Con của cặp vợ chồng ở thế hệ thứ 3 chắc chắn sẽ mắc bệnh.</p><p>(4) Cặp vợ chồng ở thế hệ thứ 2 có kiểu gen dị hợp.</p><p>(5) Có 14 người trong phả hệ này xác định được chính xác kiểu gen.</p>', '1', '2', '3', '4', '1', 2, '222'),
(101, 1, 'Trong mạch dao động LC lí tưởng đang có dao động điện từ tự do thì', 'năng lượng điện trường tập trung ở cuộn cảm.', 'năng lượng từ trường tập trung ở tụ điện.', 'năng lượng điện trường và năng lượng từ trường luôn không đổi.', 'năng lượng điện từ của mạch được bảo toàn.', 'năng lượng điện từ của mạch được bảo toàn.', 1, '105'),
(102, 2, 'tại nơi có gia tốc trọng trường là g, một con lắc lò xo treo thẳng đứng đang dao động điều hòa. Biết tại vị trí cân bằng của vật, độ dãn của lò xo là <i>Δl</i> . Tần số dao động của con lắc này là', '<img src="images/De2_2_A.jpg" alt="hinh-cau-2-de-2-vat-ly" title="cau 2 hinh de 2 vat ly thitn">', '<img src="images/De2_2_B.jpg" alt="hinh-cau-2-de-2-vat-ly" title="cau 2 hinh de 2 vat ly thitn">', '<img src="images/De2_2_C.jpg" alt="hinh-cau-2-de-2-vat-ly" title="cau 2 hinh de 2 vat ly thitn">', '<img src="images/De2_2_D.jpg" alt="hinh-cau-2-de-2-vat-ly" title="cau 2 hinh de 2 vat ly thitn">', '<img src="images/De2_2_B.jpg" alt="hinh-cau-2-de-2-vat-ly" title="cau 2 hinh de 2 vat ly thitn">', 1, '105'),
(103, 3, 'Khi có sóng dừng trên dây, khoảng cách giữa hai nút liên tiếp bằng', 'một số nguyên lần bước sóng.', 'một bước sóng.', 'một nửa bước sóng.', 'một phần tư bước sóng.', 'một nửa bước sóng.', 1, '105'),
(104, 4, 'Một con lắc đơn có chiều dài 121 cm, dao động điều hòa tại nơi có gia tốc trọng trường g = 10 m/s<sup>2</sup>. Lấy π<sup>2</sup>=10 . Chu kì dao động của con lắc là', '0,5 s.', '1 s.', '2 s.', '2,2 s.', '2,2 s.', 1, '105'),
(105, 5, 'Trong một mạch dao động LC lí tưởng gồm cuộn cảm có độ tự cảm L mắc nối tiếp với tụ điện có điện dung C đang có dao động điện từ tự do với tần số f. Hệ thức đúng là', '<img src="images/De2_5_A.jpg" alt="hinh-cau-5-de-2-vat-ly" title="cau 5 hinh de 2 vat ly thitn">', '<img src="images/De2_5_B.jpg" alt="hinh-cau-5-de-2-vat-ly" title="cau 5 hinh de 2 vat ly thitn">', '<img src="images/De2_5_C.jpg" alt="hinh-cau-5-de-2-vat-ly" title="cau 5 hinh de 2 vat ly thitn">', '<img src="images/De2_5_D.jpg" alt="hinh-cau-5-de-2-vat-ly" title="cau 5 hinh de 2 vat ly thitn">', '<img src="images/De2_5_C.jpg" alt="hinh-cau-5-de-2-vat-ly" title="cau 5 hinh de 2 vat ly thitn">', 1, '105'),
(106, 6, 'Ánh sáng có tần số lớn nhất trong số các ánh sáng đơn sắc: đỏ, lam, chàm, tím là ánh sáng', 'lam.', 'chàm.', 'tím.', 'đỏ.', 'tím.', 1, '105'),
(107, 7, 'Biểu thức li độ của vật dao động điều hòa có dạng x = Acos(ωt + φ), vận tốc của vật có giá trị cực đại là', 'v<sub>max</sub>=Aω<sup>2</sup>.', 'v<sub>max</sub>=Aω.', 'v<sub>max</sub>=2Aω.', 'v<sub>max</sub>=A<sup>2</sup>ω', 'v<sub>max</sub>=Aω.', 1, '105'),
(108, 8, 'Điện áp giữa hai đầu một đoạn mạch có biểu thức u=220cos100πt (V). Giá trị hiệu dụng của điện áp này là', '220V.', '220√2V', '110V', '110√2V', '110√2V', 1, '105'),
(109, 9, 'Một sóng âm truyền trong một môi trường. Biết cường độ âm tại một điểm gấp 100 lần cường độ âm chuẩn của âm đó thì mức cường độ âm tại điểm đó là', '50 dB.', '100 dB.', '10 dB.', '20 dB.', '20 dB.', 1, '105'),
(110, 10, 'Một chất điểm dao động điều hòa trên trục Ox theo phương trình x = 5cos4πt (x tính bằng cm, t tính bằng s). Tại thời điểm t = 5 s, vận tốc của chất điểm này có giá trị bằng', '5cm/s.', '0cm/s.', '20πcm/s.', '20πcm/s.', '0cm/s.', 1, '105'),
(111, 11, 'Trong chân không, các bức xạ được sắp xếp theo thứ tự bước sóng tăng dần là:', 'tia hồng ngoại, ánh sáng vàng, tia X, tia tử ngoại.', 'ánh sáng vàng, tia hồng ngoại, tia tử ngoại, tia X.', 'tia X, tia tử ngoại, ánh sáng vàng, tia hồng ngoại.', 'tia hồng ngoại, ánh sáng vàng, tia tử ngoại, tia X.', 'tia hồng ngoại, ánh sáng vàng, tia X, tia tử ngoại.', 1, '105');
INSERT INTO `generator` (`id`, `qno`, `question`, `opt1`, `opt2`, `opt3`, `opt4`, `ans`, `id_de`, `ma_de`) VALUES
(112, 12, 'Đặt điện áp xoay chiều u = U<sub>0</sub>cosωt vào hai đầu đoạn mạch chỉ có cuộn dây thuần cảm. Gọi U là điện áp hiệu dụng giữa hai đầu mạch; i, I<sub>0</sub> và I lần lượt là giá trị tức thời, giá trị cực đại và giá trị hiệu dụng của cường độ dòng điện trong đoạn mạch. Hệ thức nào sau đây sai?<p><img title="Đề thi thử THPT Quốc gia môn Vật lý năm 2016 tỉnh Cà Mau" src="img/de-thi-thu-thpt-quoc-gia-mon-vat-ly-nam-2016-tinh-ca-mau-2.jpg" alt="Đề thi thử THPT Quốc gia môn Vật lý năm 2016 tỉnh Cà Mau" width="100%" /></p>', 'A', 'B', 'C', 'D', 'C', 1, '105'),
(113, 13, 'Khi đặt vào 2 đầu một đoạn mạch điện một điện áp u = 220cos(ωt - π/6) (V) thì cường độ dòng điện qua mạch có biểu thức i = 2√2cos(ωt + π/12) (A). Công suất tiêu thụ của đoạn mạch là', 'P = 220√2 W.  ', 'P = 220 W.  ', 'P = 440√2 W. ', 'P = 440 W. ', 'P = 220 W.  ', 1, '105'),
(114, 14, 'Một mạch chọn sóng gồm cuộn dây thuần cảm có hệ số tự cảm L và tụ điện có điện dung C đều thay đổi được. Khi L = L<sub>1</sub> và C = C<sub>1</sub> thì mạch thu được sóng điện từ có bước sóng λ. Khi L = 3L<sub>1</sub> và C = C<sub>2</sub> thì mạch cũng thu được sóng điện từ có bước sóng λ. Nếu L = 2L<sub>1</sub> và C = C<sub>1</sub> + 3C<sub>2</sub> thì mạch thu được sóng điện từ có bước sóng là', '3λ.', '4λ.', 'λ.', '2λ.', '2λ.', 1, '105'),
(115, 15, 'Một sóng cơ truyền dọc theo trục Ox có phương trình u = Acos(20πt - πx) cm (với x tính bằng cm, t tính bằng s). Tốc độ truyền sóng trong môi trường là', '10 cm/s.', '20π cm/s.  ', '20 cm/s. ', '10π cm/s.', '20 cm/s. ', 1, '105'),
(116, 16, 'Phát biểu nào sau đây là <b>không</b> đúng khi nói về sóng điện từ?\r\nSóng điện từ', 'truyền được trong tất cả môi trường, kể cả chân không.', 'truyền đi có mang theo năng lượng.', 'có thể bị phản xạ, nhiễu xạ, ... khi gặp vật cản.', 'có tần số càng lớn, truyền trong môi trường càng nhanh.', 'có tần số càng lớn, truyền trong môi trường càng nhanh.', 1, '105'),
(117, 17, 'Một sợi dây đàn hồi AB dài 0,6 m được căng theo phương nằm ngang trong đó đầu B cố định,\r\nđầu A được rung theo phương thẳng đứng với biên độ nhỏ để tạo sóng dừng trên dây. Tần số rung của\r\nđầu A có thể thay đổi từ 16 Hz đến 26 Hz. Biết tốc độ truyền sóng trên dây v = 6 m/s. Để có sóng dừng\r\ntrên dây với đầu A coi là nút sóng thì tần số f có thể nhận các giá trị là', '20 Hz và 25 Hz.', '19 Hz và 24 Hz.', '16 Hz và 21 Hz.', '18 Hz và 23 Hz.', '20 Hz và 25 Hz.', 1, '105'),
(118, 18, 'Trong các đại lượng đặc trưng cho dòng điện xoay chiều sau đây, đại lượng nào có dùng giá\r\ntrị hiệu dụng?', 'Công suất.', 'Điện áp.', 'Chu kì.', 'Tần số.', 'Điện áp.', 1, '105'),
(119, 19, 'Khi nói về tia hồng ngoại, phát biểu nào sau đây <b>sai?</b>', 'Tia hồng ngoại có bản chất là sóng điện từ.', 'Tia hồng ngoại có bước sóng lớn hơn bước sóng của ánh sáng lục.', 'Tia hồng ngoại có tần số lớn hơn tần số của tia X.', 'Tác dụng nổi bật nhất của tia hồng ngoại là tác dụng nhiệt.', 'Tia hồng ngoại có tần số lớn hơn tần số của tia X.', 1, '105'),
(120, 20, 'Một con lắc đơn, vật nhỏ có khối lượng m và dây treo có chiều dài l . Con lắc dao động điều\r\nhòa tại nơi có gia tốc trọng trường g với tần số là', 'f = (1/2π)√(g/l)', 'f = √(l/g)', 'f = 2π√(m/g)', 'f = √(g/l)', 'f = (1/2π)√(g/l)', 1, '105'),
(121, 21, 'Công thức nào sau đây dùng để tính được bước sóng theo các thông số L, C của mạch chọn sóng máy thu vô tuyến điện ?', '<img src="images/De1_21_A.jpg" alt="hinh-cau-21-de-1-vat-ly" title="cau 21 hinh de 1 vat ly thitn">', '<img src="images/De1_21_B.jpg" alt="hinh-cau-21-de-1-vat-ly" title="cau 21 hinh de 1 vat ly thitn">', '<img src="images/De1_21_C.jpg" alt="hinh-cau-21-de-1-vat-ly" title="cau 21 hinh de 1 vat ly thitn">', '<img src="images/De1_21_D.jpg" alt="hinh-cau-21-de-1-vat-ly" title="cau 21 hinh de 1 vat ly thitn">', '<img src="images/De1_21_D.jpg" alt="hinh-cau-21-de-1-vat-ly" title="cau 21 hinh de 1 vat ly thitn">', 1, '105'),
(122, 22, 'Một chất phóng xạ có số khối là A đứng yên, phóng xạ hạt &alpha; và biến đổi thành hạt nhân X. Động lượng của hạt &alpha; khi bay ra là p. Lấy khối lượng của các hạt nhân (theo đơn vị khối lượng nguyên tử u) bằng số khối của chúng. Phản ứng tỏa năng lượng bằng', 'Ap<sup>2</sup>/2(A-4)u.', 'Ap<sup>2</sup>/(A+4)u.', 'Ap<sup>2</sup>/8(A-4)u.', 'Ap<sup>2</sup>/(A-4)u.', 'Ap<sup>2</sup>/8(A-4)u.', 1, '105'),
(123, 23, 'Gọi c là vận tốc ánh sáng trong chân không thì eV/ c<sup>2</sup> là đơn vị đo', 'năng lượng.', 'khối lượng.', 'điện tích.', 'công suất.', 'khối lượng.', 1, '105'),
(124, 24, 'Cho dòng điện xoay chiều i= π.cos(100πt-(π/2)) (A) chạy qua bình điện phân chứa dung dịch H<sub>2</sub>SO<sub>4</sub> với các điện cực bằng bạch kim. Tính điện lượng qua bình theo một chiều trong thời gian 16 phút 5 giây', '1930C', '0,02C', '965C', '867C', '965C', 1, '105'),
(125, 25, 'Đặt vào hai đầu đoạn mạch RLC không phân nhánh hiệu điện thế u = 100√2cos100πt (V) thì dòng điện qua mạch là i = √2cos100πt (A). Tổng trở thuần của đoạn mạch là', 'R = 50Ω', 'R=100Ω', 'R=20Ω', 'R=200Ω', 'R=100Ω', 1, '105'),
(126, 26, 'Một sợi dây dài 1,05 (m), hai đầu cố định được kích thích cho dao động với f = 100 (Hz) thì trên dây có sóng dừng người ta quan sát được 7 bụng sóng, tìm vận tốc truyền sóng trên dây.', '35 (m/s)', '30 (m/s)', '20 (m/s)', '10 (m/s)', '30 (m/s)', 1, '105'),
(127, 27, 'Một máy phát điện xoay chiều một pha phát ra suất điện động e = 1000√2 cos(100πt) (V). Nếu roto quay với vận tốc 600 vòng/phút thì số cặp cực là:', '8', '10', '4', '5', '5', 1, '105'),
(128, 28, 'Điều nào sau đây sai khi nói về động cơ không đồng bộ ba pha', 'Động cơ không đồng bộ ba pha biến đổi điện năng thành cơ năng', 'Tốc độ quay của khung dây luôn nhỏ hơn tốc độ quay của từ trường quay', 'Chu kỳ quay của khung dây luôn nhỏ hơn chu kỳ quay của từ trường quay ', 'Động cơ hoạt động dựa trên hiện tượng cảm ứng điện từ và sử dụng từ trường quay', 'Chu kỳ quay của khung dây luôn nhỏ hơn chu kỳ quay của từ trường quay ', 1, '105'),
(129, 29, 'Một ống Rơnghen phát ra được bức xạ có bước sóng nhỏ nhất là 0,4 nm. Để giảm bước sóng của tia Rơngen phát ra đi hai lần thì người ta phải :', 'Tăng điện áp của ống đến 3,1 KV', 'Tăng điện áp của ống thêm 3,1 KV', 'Giảm điện áp của ống đi 3,1 KV', 'Tăng điện áp của ống thêm 6,2 KV', 'Tăng điện áp của ống thêm 3,1 KV', 1, '105'),
(130, 30, 'Đặt hiệu điện thế xoay chiều u=U<sub>0</sub>cos(100πt + φ) (V) hai đầu đoạn mạch nối tiếp theo thứ tự gồm R, C và cuộn thuần cảm có độ tự cảm L. Tụ điện có điện dung C thay đổi được. Ban đầu điều chỉnh C để hiệu điện thế hiệu dụng giữa hai đầu đoạn mạch chứa R và C đạt cực đại. Sau đó, phải giảm giá trị điện dung đi ba lần thì hiệu điện thế hai đầu tụ mới đạt cực đại. Tỉ số R / Z<sub>L</sub> của đoạn mạch xấp xỉ', '2,8', '3,2', '3,6', '2,4', '3,2', 1, '105'),
(131, 31, 'Một con lắc đơn có khối lượng vật nặng là m, sợi dây mảnh có chiều dài l. Từ vị trí cân bằng, kéo\r\nvật sao cho dây treo hợp với phương thẳng đứng góc a<sub>0</sub>=60<sup>0</sup> rồi thả nhẹ. Lấy g =10 m/s<sup>2</sup> , bỏ qua mọi lực\r\ncản. Trong quá trình chuyển động thì độ lớn gia tốc của con lắc có giá trị nhỏ nhất bằng', '10√(2/3) (m/s<sup>2</sup>)', '0 (m/s<sup>2</sup>)', '10√(3/2) (m/s<sup>2</sup>)', '10√(5/3) (m/s<sup>2</sup>)', '10√(2/3) (m/s<sup>2</sup>)', 1, '105'),
(132, 32, 'Một phân xưởng cơ khí sử dụng một động cơ điện xoay chiều có hiệu suất 80%. Khi động cơ hoạt\r\nđộng sinh ra một công suất cơ là 7,5kW. Biết mỗi ngày động cơ hoạt động 8 giờ và giá tiền của một “số”\r\nđiện công nghiệp là 2000 đồng. Trong một tháng (30 ngày), số tiền mà phân xưởng đó phải trả cho ngành\r\nđiện là', '1.350.000đ', '5.400.000đ', '4.500.000đ', '2.700.000đ', '4.500.000đ', 1, '105'),
(133, 33, 'Một sợi dây đàn hồi hai đầu cố định đươc kích thích dao động với tần số không đổi. Khi lực căng\r\nsợi dây là 2,5 N thì trên dây có sóng dừng, tăng dần lực căng đến giá trị 3,6 N thì thấy xuất hiện sóng dừng\r\nlần tiếp theo. Biết tốc độ truyền sóng trên dây tỉ lệ căn bậc hai giá trị lực căng của sợi dây. Lực căng lớn nhất\r\nđể trên dây xuất hiện sóng dừng là:', '90N', '15N', '130N', '18N', '90N', 1, '105'),
(134, 34, 'Hai con lắc đơn giống hệt nhau, các quả cầu có kích thước nhỏ làm bằng chất có khối lượng riêng\r\nD = 8540 kg/m<sup>3</sup>. Dùng các con lắc nói trên để điều khiển các đồng hồ quả lắc. Đồng hồ thứ nhất đặt trong\r\nkhông khí và đồng hồ thứ hai đặt trong chân không. Biết khối lượng riêng của không khí là p = 1,3 kg/m<sup>3</sup>.\r\nBiết các điều kiện khác giống hệt nhau khi hai đồng hồ hoạt động. Nếu coi đồng hồ trong chân không chạy\r\nđúng thì đồng hồ đặt trong không khí chạy nhanh hay chậm bao nhiêu sau một ngày đêm.', '6,58 giây', '2,15 giây', '3,98 giây', '8,24 giây', '6,58 giây', 1, '105'),
(135, 35, 'Một chất điểm dao động điều hòa với phương trình:x = 20cos(πt -5π/6) cm . Tại thời điểm 1 t gia tốc\r\ncủa chất điểm có giá trị cực tiểu. Tại thời điểm   t<sub>1</sub> = t<sub>2</sub> + Δt (trong đó  t<sub>2</sub> < 2013T ) thì tốc độ của chất điểm là\r\n10π√2 cm/s. Giá trị lớn nhất của Δt là', '4025,75s.', '4024,25s', '4025,25s', '4024,75s', '4024,75s', 1, '105'),
(136, 36, 'Tại hai điểm A và B trên mặt nước cách nhau 16cm có hai nguồn phát sóng giống nhau. Điểm M\r\nnằm trên mặt nước và trên đường trung trực của AB cách trung điểm I của AB một khoảng nhỏ nhất bằng\r\n4√5 cm luôn dao động cùng pha với I. Điểm N nằm trên mặt nước và nằm trên đường thẳng vuông góc với\r\nAB tại A, cách A một khoảng nhỏ nhất bằng bao nhiêu để N dao động với biên độ cực tiểu?', '9,22cm', '8,75cm', '2,14cm', '8,57cm', '2,14cm', 1, '105'),
(137, 37, 'Đặt điện áp xoay chiều có giá trị hiệu dụng không đổi 150V vào 2 đầu mạch AB gồm AM chỉ chứa R,\r\nđoạn mạch MB chứa tụ C và cuộn cảm thuần L nối tiếp, L thay đổi được. Biết sau khi thay đổi L thì điện áp hiệu\r\ndụng 2 đầu mạch MB tăng 2√2 lần và dòng điện trước và sau khi thay đổi L lệch pha nhau π/2. Điện áp hiệu dụng 2 đầu mạch AM khi chưa thay đổi L là\r\nA.100', '100√2 V', '120V', '100V', '100√3', '100√2 V', 1, '105'),
(138, 38, 'Vật có khối lượng 400 g dao động điều hoà có đồ thị động năng\r\nnhư hình vẽ. Tại thời điểm t = 0 vật đang chuyển động theo chiều\r\ndương, lấy π <sup>2</sup> ≈ 10 . Phương trình dao động của vật là:<br>\r\n<img src="img/cau_38_de_8.jpg" alt="hinh-38-de-ly-thai-to" title="hinhc cau 38 de ly thai to" width="50%">', 'x = 10cos(πt + π / 6) (cm) .', 'x = 10cos(πt - π / 3) (cm) .', 'x = 5cos(2πt - π / 3) (cm) .', 'x = 5cos(2πt + π / 3) (cm) .', '5cos(2πt - π / 3) (cm) .', 1, '105'),
(139, 39, 'Hai nguồn phát sóng kết hợp A, B với AB = 16cm trên mặt\r\nthoáng chất lỏng, dao động theo phương trình u<sub>A</sub> = 5cos(30πt)mm ; u<sub>B</sub> = 5cos(30πt + π/2)  mm .Coi biên độ sóng không đổi, tốc độ sóng v = 60cm/ s. Gọi O là\r\ntrung điểm của AB, điểm đứng yên trên đoạn AB gần O nhất và xa O nhất cách O một đoạn tương ứng là', '1 cm; 6,5 cm.', '0,5 cm; 7,5 cm.', '0,25 cm; 7,75 cm.', '1cm; 8 cm.', '0,5 cm; 7,5 cm.', 1, '105'),
(140, 40, 'Con lắc lò xo thẳng đứng, lò xo có độ cứng k = 100N/m, vật nặng có khối lượng m = 1kg. Nâng vật\r\nlên cho lò xo có chiều dài tự nhiên rồi thả nhẹ để con lắc dao động. Bỏ qua mọi lực cản. Khi vật m tới vị trí\r\nthấp nhất thì nó tự động được gắn thêm vật m<sup>0</sup> = 500g một cách nhẹ nhàng. Chọn gốc thế năng là vị trí cân\r\nbằng. Lấy g = 10m/s<sup>2</sup>. Hỏi năng lượng dao động của hệ thay đổi một lượng bằng bao nhiêu?', 'Tăng 0,25J', 'Tăng 0,125J', 'Giảm 0,25J', 'Giảm 0,375J', 'Giảm 0,375J', 1, '105'),
(141, 41, 'Một vật dao động điều hòa với biên độ A = 5 cm, khi vật có li độ 2,5cm thì tốc độ của vật là\r\n5√3 cm/s. Hãy xác định vận tốc cực đại của dao động?', '10 m/s', '8 cm/s', '10 cm/s', '8 m/s', '10 m/s', 1, '105'),
(142, 42, 'Trong mạch dao động LC lí tưởng có dao động điện từ tự do thì', 'năng lượng điện trường tập trung ở cuộn cảm.', 'năng lượng điện trường và năng lượng từ trường luôn không đổi.', 'năng lượng từ trường tập trung ở tụ điện.', 'năng lượng điện từ của mạch được bảo toàn.', 'năng lượng điện từ của mạch được bảo toàn.', 1, '105'),
(143, 43, 'Khi có sóng dừng trên một sợi dây đàn hồi, khoảng cách từ một bụng đến nút gần nó nhất bằng', 'một nửa bước sóng.', 'một số nguyên lần bước sóng.', 'một phần tư bước sóng.', 'một bước sóng.', 'một phần tư bước sóng.', 1, '105'),
(144, 44, 'Mạch dao động điện từ lí tưởng gồm cuộn thuần cảm và hai tụ điện giống nhau mắc nối tiếp,hai bản\r\ncủa một tụ được nối với nhau bằng một khóa K. Ban đầu khóa K mở, cung cấp năng lượng cho mạch dao\r\nđộng thì điện áp cực đại giữa 2 đầu cuộn dây là 8√6 V. Sau đó đúng vào lúc thời điểm dòng điện qua cuộn\r\ndây có cường độ bằng giá trị hiệu dụng thì đóng khóa K .Điện áp cực đại giữa 2 đầu cuộn dây sau khi K\r\nđóng là', '9 V', '10 V', '12 V', '6 V', '12 V', 1, '105'),
(145, 45, 'Trong sơ đồ của một máy phát sóng vô tuyến điện, không có mạch (tầng)', 'tách sóng', 'khuếch đại', 'phát dao động cao tần', 'biến điệu', 'tách sóng', 1, '105'),
(146, 46, 'Một mạch dao động LC lí tưởng, gồm cuộn cảm thuần có độ tự cảm L và tụ điện có điện dung C.\r\nTrong mạch có dao động điện từ tự do. Gọi U<sub>0</sub>, I<sub>0</sub> lần lượt là hiệu điện thế cực đại giữa hai đầu tụ điện và\r\ncường độ dòng điện cực đại trong mạch thì', 'U<sub>0</sub>= I<sub>0</sub>/√(L/C)', 'U<sub>0</sub>= I<sub>0</sub>√(L/C)', 'U<sub>0</sub>= I<sub>0</sub>√(C/L)', 'U<sub>0</sub>= I<sub>0</sub>√(L/C)', 'U<sub>0</sub>= I<sub>0</sub>√(L/C)', 1, '105'),
(147, 47, 'Một mạch dao động điện từ LC lí tưởng gồm cuộn cảm thuần độ tự cảm L và tụ điện có điện dung\r\nthay đổi được từ C1 đến C2. Mạch dao động này có chu kì dao động riêng thay đổi được.', 'từ 4π√(LC<sub>1</sub>) đến 4π√(LC<sub>2</sub>)', 'từ 2π√(LC<sub>1</sub>)  đến 2π√(LC<sub>2</sub>)', 'từ 2√(LC<sub>1</sub>)  đến 4√(LC<sub>2</sub>)', 'từ 4√(LC<sub>1</sub>)  đến 4√(LC<sub>2</sub>)', 'từ 2π√(LC<sub>1</sub>)  đến 2π√(LC<sub>2</sub>)', 1, '105'),
(148, 48, 'Một con lắc lò xo treo thẳng đứng gồm vật nhỏ m gắn vào một đầu lò xo có chiều dài lo thì dao\r\nđộng điều hòa với chu kì To = 1,5 s. Cắt bỏ chiều dài lò xo này đi lo/3 thì khi treo vật m vào, hệ sẽ dao động\r\nvới chu kì T bằng bao nhiêu', '1,225s', '0,577s', '1,73s', '1s', '1s', 1, '105'),
(149, 49, 'Một vật nhỏ có khối lượng 100g dao động điều hòa với chu kì 0,5π s và biên độ 3cm. Chọn mốc\r\nthế năng tại vi trí cân bằng, cơ năng của vật là', '0,18 mJ', '0,36 mJ', '0,48 mJ', '0,72 mJ', '0,72 mJ', 1, '105'),
(150, 50, 'Tại hai điểm A và B trên mặt nước cách nhau 16cm có hai nguồn sóng giống nhau. Điểm M nằm\r\ntrên mặt nước và trên đường trung trực của AB cách trung điểm I của AB một khoảng nhỏ nhất bằng 4√5\r\ncm luôn dao động cùng pha với I. Điểm N nằm trên mặt nước và nằm trên đường thẳng vuông góc với AB\r\ntại A, cách A một khoảng nhỏ nhất bằng bao nhiêu để N dao động với biên độ cực tiểu?', '9,22cm', '7,75cm', '2,14cm', '8,57cm', '2,14cm', 1, '105');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `user` varchar(256) CHARACTER SET latin1 NOT NULL,
  `password` varchar(256) CHARACTER SET latin1 NOT NULL,
  `email` varchar(256) CHARACTER SET latin1 NOT NULL,
  `phone` varchar(256) CHARACTER SET latin1 NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Contenu de la table `users`
--

INSERT INTO `users` (`user`, `password`, `email`, `phone`) VALUES
('chauminhthien', 'chauminhthien', 'minhthien1305@gmail.com', ' 0123456789'),
('NguyenHung', 'hung1903', 'tronghunghghk@gmail.com', '01675726900'),
('tranhuuphuoc', 'tranhuuphuoc', 'phucdangb1400718@gmail.com', '0123456789'),
('phucdang', '12345', 'phucdangb1400718@gmail.com', '0123456789'),
('keeloren', 'loveyou25', 'keezimin@gmail.com', '01654568408'),
('khanhieu', 'khanhieu', 'phucdangb1400718@gmail.com', '0123456789'),
('pixsnguyen', 'khanhieu', 'nknplay@gmail.com', '01223900576'),
('username', 'thithpt.tk', 'phuocb1400720@gmail.com', '01674027211'),
('phucdang1', 'phucdang1', 'phucdangb1400718@gmail.com', '0123456789'),
('nviethuan', 'nauhteiv15', 'ngnviethuan@gmail.com', '01649178235'),
('dangchau', 'dangkhoa', 'lddchau@gmail.com', '01627558448'),
('KimAnh', 'KimAnh22112000', 'KimAnh@gmail.com', '01864420669'),
('sysadmin', '123', 'abc@bca.ccc', '01234567890'),
('danglevinhkhoa', 'danglevinhkhoa', 'khoab1406265@student.ctu.edu.vn', '01884555860'),
('Trinh Ung', '12345678', 'ktrinhkst13@gmail.com', '01648988723'),
('superlaze', 'johncena', 'hoaivantanka@gmail.com', '1111111111111'),
('danghoangdiu', '250794', 'danghoangdiu@gmail.com', '0981536532'),
('phucdang123', 'phucdang123', 'phucdang123@gmail.com', '01234567891'),
('phucdang1234', 'phucdang1234', 'phucdangb1400718@gmail.com', '0923167564'),
('Meo Meo', 'matkhau', 'trinhtrami1999@gmail.com', '01202158793'),
('nganh0509', '01683223794', 'nganh0509@gmail.com', '01682332794'),
('miupham1804@gmail.com', '123456789', 'miupham1804@gmail.com', '0913558791'),
('dangphuc', 'dangphuc', 'phucdangb1400718@gmail.com', '0923145678');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
